/* eslint-disable no-unused-vars */
import React from 'react'

function Main() {
  return (
    <div className='  p-6 md:p-8'>
        <div className='py-8'>
            <h1 className=' text-4xl font-extrabold py-4'>The showcase image generation is here</h1>
            <p>Browse through the collection of imaginative and visually stunning images<br/> generated by DALL-E-AI</p>
        </div>
    </div>
  )
}

export default Main